### ISSUE TITLE
shard install failed with crystal 1.0.0

### ISSUE THREAD

**Issue by RokkuCode** [MakeNowJust/crustache#31]
shards.yml
```yml
  crustache:
    github: MakeNowJust/crustache
    version: ~> 2.4.3
```
Error message:
```
- `crystal (~> 0.34, >= 0.34.0)` required by `crustache 2.4.3`
```
In the head of the repository this is fixed, but there is no release with this fix. So if people want to pin the current released version of custache they are not able to install it. Please make a release with the fix.

There are more errors. If i define the shards.yml like this:
```yml
  crustache:
    github: MakeNowJust/crustache
```
Error msg:
```
Resolving dependencies
Fetching https://github.com/makenowjust/crustache.git
Unable to satisfy the following requirements:

- `crystal (< 1.0.0)` required by `crustache 2.4.1`
```
It falls down to crustache 2.4.1

**Comment by RokkuCode** [comment]
Current workaround
```yml
  crustache:
    github: MakeNowJust/crustache
    branch: master
```
